### PR TITLE
AST - Fix starting sect not recognized

### LINKED ISSUE #1014: bug: AST 'no sect' suggestion appears while sect-related skills are logged
Log info: KOR server, patch 5.20
Original Log: https://www.fflogs.com/reports/P7gcfGQZka8dF1h9#fight=last&type=summary
Example: https://xivanalysis.com/fflogs/P7gcfGQZka8dF1h9/10/3578

In this report, the suggestion module suggests 'use Diurnal Sect or Nocturnal Sect'. but below the suggestion module, the used sect has appeared and sect-related skills are logged.

(I'm not sure issue report is allowed and the format of this report is valid, if this is invalid, please close this issue)

### PR DESCRIPTION
**Pull request by CasualSuperman**
Fixes #1014
The Sect module was treating the action fabricated by the PrecastStatus module as an actual stance activation. There might a better way to detect this than what I've got, but I didn't see any extra properties added by PrecastStatus that would allow distinguishing between fabricated and real events.

### CODE REVIEW

File: src/parser/jobs/ast/index.tsx [hunk 1]
```diff
@@ -34,8 +34,16 @@ export default new Meta({
 	},
 	contributors: [
 		{user: CONTRIBUTORS.SUSHIROU, role: ROLES.MAINTAINER},
+		{user: CONTRIBUTORS.CASUALSUPERMAN, role: ROLES.DEVELOPER},
 	],
 	changelog: [
+		{
+			date: new Date('2020-09-30'),
+			Changes: () => <>
+				Fixed bug where starting stance was always reported forgotten.
```
Comment (ayyaruq) [inline src/parser/jobs/ast/index.tsx:43]: Can we reword this so that it doesn't sound like you had a stroke mid-sentence?

File: src/parser/jobs/ast/modules/Sect/Sect.tsx [hunk 2]
```diff
@@ -142,8 +142,9 @@ export default class Sect extends Module {
 	}
 
 	private onCast(event: CastEvent) {
-		// If they casted a sect at anytime it means they pulled without one on
-		this.pullWithoutSect = true
+		// If they used a sect after the fight started, it means they pulled without one on; otherwise, it was likely added by the PrecastStatus module.
+		this.pullWithoutSect = event.timestamp >= this.parser.eventTimeOffset
```
Comment (ayyaruq) [inline src/parser/jobs/ast/modules/Sect/Sect.tsx:146]: Any reason to use `eventTimeOffset` over `start_time`?

**Review by ayyaruq — CHANGES_REQUESTED** [review]
Question on your timestamp aside, the changelog message could really be clearer as to what it's doing. I'm not sure how Precast could cause the issue you're talking about in the comment though unless they remove it after combat, because Precast relies ons seeing the status fall off.

File: src/parser/jobs/ast/modules/Sect/Sect.tsx (hunk 2 above)
Comment (CasualSuperman) [reply src/parser/jobs/ast/modules/Sect/Sect.tsx:146]: Nope

> Question on your timestamp aside, the changelog message could really be clearer as to what it's doing. I'm not sure how Precast could cause the issue you're talking about in the comment though unless they remove it after combat, because Precast relies ons seeing the status fall off.

I thought the aspected heals had a `statusesApplied` section, but looking at it they actually don't. It's being done by this module's own `normalize`.

File: src/parser/jobs/ast/index.tsx (hunk 1 above)
Comment (CasualSuperman) [reply src/parser/jobs/ast/index.tsx:43]: ... sure

**Review by ayyaruq — APPROVED** [review]
