### PR TITLE
Fix Aspected Benefic's ability id

### LINKED ISSUE #1045: Aspected Benefic missing from GCD row of Timeline
Both versions of Aspected Benefic show as blank spaces in the timeline view. AST is a bit out of my scope so maybe helpful if @suShirow or @CasualSuperman take a look.

The Nocturnal Sect version has an incorrect ID so this is understandable (although how does any of the job logic not break?), it's currently `17151` however should be `3595` and hasn't changed since 5.0 so this'll need a fix in the actions root. Diurnal Sect is correctly 835, however I'll note fflogs sends this one with the 1000000 guid adjustment. Shouldn't cause an issue though.

Example log provided by initial reporter in Discord, with Diurnal Sect: https://www.fflogs.com/reports/hWK1a7pB268CxkVJ#fight=8&type=casts&source=22&view=timeline

It literally renders a gap in the timeline, for example in this screenshot, it was used between the Malefic and Lucid. There is no loading error in the dev console, so it appears to not even be trying to fetch it.
image

### PR DESCRIPTION
**Pull request by CasualSuperman**
Fixes #1045

The incorrect ID appears to be Diurnal's Aspected Benefic. I created [this minimal log](https://www.fflogs.com/reports/26y8HKtg97WfZzDC) with a few casts in each sect to verify. The first encounter is in Nocturnal, the second is Diurnal.

After updating the diurnal id, the casts appear in the timeline for me in both sects.
I found some mismatched buffs in the sect detection module while tracking this down, so I corrected those as well.

### CODE REVIEW

File: src/parser/jobs/ast/modules/Sect/Sect.tsx [hunk 1]
```diff
@@ -113,12 +113,10 @@ export default class Sect extends Module {
 				aspectedCast = event
 
 			} else if (aspectedCast
-				&& (event.type === 'applybuff' || event.type === 'refreshbuff') && [...NOCTURNAL_SECT_STATUSES, ...DIURNAL_SECT_STATUSES].includes(event.ability.guid)) {
+				&& (event.type === 'applybuff' || event.type === 'refreshbuff') && SECT_BUFF_STATUSES.includes(event.ability.guid)) {
 				// This is an applybuff event of a sect buff that came after an aspected action
 
-				if (this.mapCastToBuff(aspectedCast.ability.guid).includes(event.ability.guid)
-					&& [...DIURNAL_SECT_STATUSES, ...NOCTURNAL_SECT_STATUSES].includes(event.ability.guid)) {
```
Comment (CasualSuperman) [inline src/parser/jobs/ast/modules/Sect/Sect.tsx:120]: This part was redundant since the enclosing if checked the same thing already.

File: src/parser/jobs/ast/modules/Sect/Sect.tsx [hunk 2]
```diff
@@ -37,24 +29,32 @@ const NOCTURNAL_SECT_STATUSES = [
...
 
-const ACTION_STATUS_MAP = {
-	[ACTIONS.ASPECTED_BENEFIC.id]: [
-		STATUSES.ASPECTED_BENEFIC.id,
-		STATUSES.NOCTURNAL_FIELD.id,
-	],
-	[ACTIONS.ASPECTED_HELIOS.id]: [
+const SECT_BUFF_STATUSES = [...NOCTURNAL_SECT_STATUSES, ...DIURNAL_SECT_STATUSES]
+
+const ACTION_STATUS_MAP: Map<number, number[]> = new Map([
```
Comment (nonowazu) [inline src/parser/jobs/ast/modules/Sect/Sect.tsx:34]: This PR says "Fix Aspected Benefic's ability id", but this PR seems to do a lot more (like adding type annotations, swapping objects with a Map, etc).

I'd strongly prefer if you either changed this PR to be about type changing / cleanup and remove the ID changes (and rename the PR), or remove these type/code cleanups and PR them separately.

**Review by nonowazu — CHANGES_REQUESTED** [review]

File: src/parser/jobs/ast/modules/Sect/Sect.tsx (hunk 2 above)
Comment (CasualSuperman) [reply src/parser/jobs/ast/modules/Sect/Sect.tsx:34]: Sure, I'll split them up tomorrow

File: src/data/ACTIONS/root/AST.ts [hunk 3]
```diff
@@ -121,8 +121,8 @@ export const AST = ensureActions({
 		mpCost: 1000,
 	},
 
-	ASPECTED_BENEFIC: {
-		id: 835,
+	ASPECTED_BENEFIC: { // Diurnal Variant
+		id: 3595,
```
Comment (ayyaruq) [inline src/data/ACTIONS/root/AST.ts:125]: 835 is correct, Noct should be 3595 instead of 17000ish.

**Review by ayyaruq — CHANGES_REQUESTED** [review]
Echoing Nono but you seem to have changed the ID for the wrong variant of Aspected Benefic, unless something else is going on. I see logs with both 835 and 3595 (when iirc you can't change stance mid combat?) but the 17k value never shows up at all. Could be a case of multiple IDs for one skill tho, or a buff changing the ID. Might help to run some dummy logs using both stances and any buffs that effect the skill and seeing what we get. Happy to help analyse them if you choose to do so.

**Comment by AzariahAeroborn** [comment]
> Echoing Nono but you seem to have changed the ID for the wrong variant of Aspected Benefic, unless something else is going on. I see logs with both 835 and 3595 (when iirc you can't change stance mid combat?) but the 17k value never shows up at all.

You can't change stance, but you can use Neutral Sect, which then applies both regardless of stance. Though my recollection is that the noct shield applied by Neutral when in diurnal is a different buff than "true" noct shield, so there are probably three different IDs in play here.

**Comment by CasualSuperman** [comment]
> I see logs with both 835 and 3595 (when iirc you can't change stance mid combat?)

You can apply nocturnal benefic pre-pull, then swap. It's relatively common. If you're seeing both in later combat then something could be up. 

> Might help to run some dummy logs using both stances and any buffs that effect the skill and seeing what we get. Happy to help analyse them if you choose to do so.

I did do this, log is linked in the initial PR comment (on mobile or I'd grab it myself)

**Comment by CasualSuperman** [comment]
Created and uploaded another log: https://www.fflogs.com/reports/Z19WKMFwkgTh3LnR/

The first encounter is in _Diurnal_ sect. I see these `cast` ids:
```
events[6]: {ability: {name: "Diurnal Sect", guid: 3604, type: 1, abilityIcon: "003000-003133.png"}}
events[8]: {ability: {name: "Aspected Benefic", guid: 3595, type: 8, abilityIcon: "003000-003127.png"}}
events[21]: {ability: {name: "Aspected Helios", guid: 3601, type: 8, abilityIcon: "003000-003130.png"}}
events[38]: {ability: {name: "Celestial Intersection", guid: 16556, type: 8, abilityIcon: "003000-003556.png"}}
events[49]: {ability: {name: "Celestial Opposition", guid: 16553, type: 8, abilityIcon: "003000-003142.png"}}
```
And these `applybuff` ids:
```
events[7]: {ability: {name: "Diurnal Sect", guid: 1000839, type: 1, abilityIcon: "013000-013218.png"}}
events[11]: {ability: {name: "Aspected Benefic", guid: 1000835, type: 8, abilityIcon: "013000-013215.png"}
events[26]: {ability: {name: "Aspected Helios", guid: 1000836, type: 8, abilityIcon: "013000-013216.png"}}
events[41]: {ability: {name: "Nocturnal Intersection", guid: 1001889, type: 8, abilityIcon: "013000-013250.png"}}
events[54]: {ability: {name: "Diurnal Opposition", guid: 1001879, type: 8, abilityIcon: "013000-013246.png"}}
```

The second encounter is in Nocturnal sect.
`cast`s:
```
events[9]: {ability: {name: "Nocturnal Sect", guid: 3605, type: 1, abilityIcon: "003000-003134.png"}}
events[12]: {ability: {name: "Aspected Benefic", guid: 17151, type: 8, abilityIcon: "003000-003127.png"}}
events[22]: {ability: {name: "Aspected Helios", guid: 17152, type: 8, abilityIcon: "003000-003130.png"}}
events[31]: {ability: {name: "Celestial Opposition", guid: 16553, type: 8, abilityIcon: "003000-003142.png"}}
events[59]: {ability: {name: "Celestial Intersection", guid: 16556, type: 8, abilityIcon: "003000-003556.png"}}
```
`applybuff`s:
```
events[10]: {ability: {name: "Nocturnal Sect", guid: 1000840, type: 1, abilityIcon: "013000-013219.png"}}
events[15]: {ability: {name: "Nocturnal Field", guid: 1000837, type: 8, abilityIcon: "013000-013217.png"}}
events[25]: {ability: {name: "Nocturnal Field", guid: 1000837, type: 8, abilityIcon: "013000-013217.png"}}
events[34]: {ability: {name: "Nocturnal Opposition", guid: 1001880, type: 8, abilityIcon: "013000-013247.png"}}
events[62]: {ability: {name: "Diurnal Intersection", guid: 1001888, type: 8, abilityIcon: "013000-013249.png"}}
```
I also tried casting cast Neutral Sect while in Nocturnal stance, the resulting buffs are indeed distinct from the typical buffs from Aspected Benefic/Helios.
```
events[38]: {ability: {name: "Neutral Sect", guid: 16559, type: 1, abilityIcon: "003000-003552.png"}}
```
Cast Aspected Benefic (Nocturnal):
```
events[41]: {ability: {name: "Aspected Benefic", guid: 17151, type: 8, abilityIcon: "003000-003127.png"}}
```
Which produced these `applybuff`s:
```
events[44]: {ability: {name: "Nocturnal Field", guid: 1000837, type: 8, abilityIcon: "013000-013217.png"}}
events[45]: {ability: {name: "Diurnal Balance", guid: 1001920, type: 8, abilityIcon: "013000-013254.png"}}
```
And then `cast` Aspected Helios (Nocturnal):
```
events[55]: {ability: {name: "Aspected Helios", guid: 17152, type: 8, abilityIcon: "003000-003130.png"}}
```
Which produced this `applybuff`: (interestingly, no ability name was provided from fflogs)
```
events[58]: {ability: {name: "", guid: 1001247, type: 1, abilityIcon: "000000-000405.png"}}
```

These ability IDs all match what is in the repo, minus Diurnal Sect's Aspected Benefic.

File: src/data/ACTIONS/root/AST.ts (hunk 3 above)
Comment (CasualSuperman) [reply src/data/ACTIONS/root/AST.ts:125]: 835 is the `applybuff` id, not the `cast` id.

Comment (ayyaruq) [reply src/data/ACTIONS/root/AST.ts:125]: Ah the Status, not the Action, oops.

**Comment by ayyaruq** [comment]
Thanks for the thorough investigation, that makes sense now. So as far as the PR goes, I think we can just strip out the commits not touching the IDs, and maybe make the changelog more descriptive. While we love code quality improvements, it's a lot easier to review PRs and scope changes when one PR contains only one changeset.

File: src/parser/jobs/ast/index.tsx [hunk 4]
```diff
@@ -37,6 +37,13 @@ export default new Meta({
 		{user: CONTRIBUTORS.CASUALSUPERMAN, role: ROLES.DEVELOPER},
 	],
 	changelog: [
+		{
+			date: new Date('2020-12-01'),
+			Changes: () => <>
+				Fixed <ActionLink {...ACTIONS.ASPECTED_BENEFIC} /> detection.
```
Comment (ayyaruq) [inline src/parser/jobs/ast/index.tsx:43]:
```suggestion
				Fix incorrect action ID and timeline view for Diurnal Sect <ActionLink {...ACTIONS.ASPECTED_BENEFIC} />.
```

**Review by ayyaruq — CHANGES_REQUESTED** [review]
Small cleanup on changelog to be clearer, you can just hit the approve suggestion button and I'll merge. Thanks!

**Review by ayyaruq — APPROVED** [review]
Awesome, thanks!
